

sudo: required
services: docker
before_install:
  - docker build -t local docker/python
  - docker pull node:12.8.0-buster
script:
  - docker run -v "$(pwd):/srv" -w/srv node:12.8.0-buster make build
  - docker run -v "$(pwd):/srv" -w/srv local make install demo
